name: "F-Droid Update"

on:
  release:
    types: [published]

jobs:
  fdroid-update:
    name: "Update F-Droid"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout RUTMath repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Extract version info"
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION_NAME=${TAG_NAME#v}
          
          # Extract versionCode from androidApp/build.gradle
          VERSION_CODE=$(grep -Po 'versionCode\s+\K\d+' androidApp/build.gradle)
          
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: "Checkout F-Droid Data repository"
        uses: "actions/checkout@v4"
        with:
          repository: 'f-droid/fdroiddata'
          token: ${{ secrets.FDROID_TOKEN }}
          path: 'fdroiddata'

      - name: "Update F-Droid metadata"
        run: |
          cd fdroiddata
          
          # Create or update metadata file
          mkdir -p metadata
          
          cat > metadata/com.hexbit.rutmath.yml << 'EOF'
          Categories:
            - Games
            - Science & Education
          License: GPL-3.0-or-later
          AuthorName: Arkadiusz Połeć
          AuthorEmail: apolec01@st.prz.edu.pl
          WebSite: https://github.com/przemarbor/RUTMath
          SourceCode: https://github.com/przemarbor/RUTMath
          IssueTracker: https://github.com/przemarbor/RUTMath/issues
          Changelog: https://github.com/przemarbor/RUTMath/releases

          AutoName: RUTMath
          Name: RUTMath

          RepoType: git
          Repo: https://github.com/przemarbor/RUTMath.git

          Builds:
            - versionName: ${{ steps.version.outputs.version_name }}
              versionCode: ${{ steps.version.outputs.version_code }}
              commit: ${{ steps.version.outputs.tag_name }}
              subdir: androidApp
              gradle:
                - release
              prebuild: echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8' >> ../gradle.properties

          MaintainerNotes: |
            This is a Kotlin Multiplatform Mobile project.
            The Android app is built from the androidApp subdirectory.

          AutoUpdateMode: Version
          UpdateCheckMode: Tags
          CurrentVersion: ${{ steps.version.outputs.version_name }}
          CurrentVersionCode: ${{ steps.version.outputs.version_code }}
          EOF

      - name: "Create Pull Request to F-Droid"
        uses: "peter-evans/create-pull-request@v5"
        with:
          token: ${{ secrets.FDROID_TOKEN }}
          path: fdroiddata
          commit-message: "Update RUTMath to ${{ steps.version.outputs.version_name }} (${{ steps.version.outputs.version_code }})"
          title: "Update RUTMath to ${{ steps.version.outputs.version_name }}"
          body: |
            Update RUTMath to version ${{ steps.version.outputs.version_name }} (version code ${{ steps.version.outputs.version_code }})
            
            Release notes: ${{ github.event.release.html_url }}
            
            Auto-generated by GitHub Actions from: ${{ github.event.repository.html_url }}
          branch: "update-rutmath-${{ steps.version.outputs.version_name }}"
          delete-branch: true 