name: "Release"

on:
  push:
    tags:
      - "v*" # np. v0.2.3
  workflow_dispatch:












jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write

      
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Decode keystore"
        run: echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode > androidApp/release.keystore

      - name: "Set up signing env"
        run: |
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "SIGNING_KEYSTORE_PASSWORD=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
        
      - name: "Build Release APK"
        run: ./gradlew androidApp:assembleRelease --no-daemon

      - name: "Upload APK artifact"
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: androidApp/build/outputs/apk/release/androidApp-release.apk

      - name: "Build Release AAB"
        run: ./gradlew androidApp:bundleRelease --no-daemon

      - name: "Upload AAB artifact"
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: androidApp/build/outputs/bundle/release/androidApp-release.aab

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            androidApp/build/outputs/apk/release/androidApp-release.apk
            androidApp/build/outputs/bundle/release/androidApp-release.aab
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
