# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        
      - name: "Setup Java"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: "Setup Gradle"
        uses: "gradle/gradle-build-action@v3"
        with:
          generate-job-summary: false

      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"

      - name: "Build Release APK"
        run: "./gradlew androidApp:assembleRelease --no-daemon"

      - name: "Build Release AAB"
        run: "./gradlew androidApp:bundleRelease --no-daemon"

      - name: "Create GitHub Release"
        uses: "softprops/action-gh-release@v1"
        with:
          files: |
            androidApp/build/outputs/apk/release/androidApp-release.apk
            androidApp/build/outputs/bundle/release/androidApp-release.aab
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}