name: Manual Date Display Workflow

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  show-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Show start time
        run: |
          echo "🔹 Workflow started at: $(date)"

      - name: Simulate work (sleep 5 seconds)
        run: sleep 5

      - name: Show end time
        run: |
          echo "✅ Workflow ended at: $(date)"
